### ISSUE TITLE
QUESTION: what is the limitation of webGL - glsl example

### ISSUE THREAD

**Issue by JakubKoralewski** [danyshaanan/mandelbrot#1]
When you zoom in on the two of the sets in the [glsl example](https://danyshaanan.github.io/mandelbrot/glsl) you get pixely stuff. Why is that? What limitations are present?
[![obraz](https://user-images.githubusercontent.com/43069023/71738134-0be76280-2e56-11ea-8876-3576f1e3ea29.png)](https://danyshaanan.github.io/mandelbrot/glsl/?0.015476873886018136,0.848526962746175,2.4234625167790624e-9,-0.003019282144664286,0.017224461496788326,7.057908193109267e-8)

**Comment by danyshaanan** [comment]
This will happen in most implementations. Once you zoom in enough, your floats resolution is not good enough, and very close numbers will rounded up to be the same, therefore whole regions will be rendered as the same color. The location you're at, (as well as the language's treatment of floats and calculations) would determine the size and orientation of the regions.

Example from Canvas (JS) version:
![image](https://user-images.githubusercontent.com/1116738/71997556-bd1b3d80-3246-11ea-9609-1bfa495148a7.png)

Example from NodeJS version:
![image](https://user-images.githubusercontent.com/1116738/71997624-de7c2980-3246-11ea-894b-af888f0fb7a3.png)

Note that both those are JS and therefore it's not surprising that the orientation of the artifacts is the same. The fact that it is horizontal might point to the numbers being rounded off before any iteration. (unlike in glsl).

**Comment by JakubKoralewski** [comment]
@danyshaanan I am currently implementing the same thing in Rust (and will be happy to PR and add it later) with shaders. Do you think think this can be mitigated somehow? By using some `Big Number` struct to achieve higher levels of precision?

**Comment by danyshaanan** [comment]
Theoretically, it surely can. I'm not familiar with `Big Number` and therefore can't predict if it will mitigate the issue, or just make it happen at even smaller numbers, but it's surely worth a try, and an implementation that can go into infinity would certainly be cool.
